AWSTemplateFormatVersion: '2010-09-09'
Description: 'TP AWS Lambda - Code charge depuis src/main.py'

Parameters:
  Environment:
    Type: String
    Description: 'Environnement name (e.g. votre identifiant sans le learnaws)'
    Default: 'kdakou'
  BucketName:
    Type: String
    Description: 'S3 bucket name'
    Default: 's3-bucket-trigger-lambda'

Resources:
  # Rôle IAM pour la fonction Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
          Action: [sts:AssumeRole]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole 
      Policies:
        - PolicyName: LambdaS3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: [s3:GetObject, s3:PutObject]
                Resource: !Sub 'arn:aws:s3:::${Environment}-${BucketName}/*'
              - Effect: Allow
                Action: [dynamodb:PutItem, dynamodb:GetItem]
                Resource: '*'

  # Fonction Lambda
  LambdaTrigger:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${Environment}-lambda-trigger'
      Handler: main.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.12
      Code: ../src

  # PERMISSION: Autoriser S3 à invoquer Lambda (AJOUTER CETTE SECTION)
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaTrigger
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::${Environment}-${BucketName}'

  # S3 bucket
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${Environment}-${BucketName}'
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt LambdaTrigger.Arn